spring:
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  datasource:
    username: sa
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    password: Hello
  jpa:
    database-open-in-view: 'false'
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl:
        auto: create
server:
  port: '8080'

